version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: health_app
    container_name: health_app
    restart: unless-stopped
    tty: true
    volumes:
       - ./source_code:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      SERVICE_NAME: health_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: health_webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./source_code:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: health_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: health_app
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
