version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hitpay_test
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
       - ./src:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001 remote_enable=1
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: hitpay-webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/log:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  database:
    image: mysql:5.7.22
    container_name: dbmysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hitpay
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: dbmysql
    volumes:
      - ./db/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
